#!/bin/bash -l
GIT_REPO=/home/as/repos/awesomeblog.git
#repos/awesomeblog.git
TMP_GIT_CLONE=/home/as/tmp
PUBLIC_WWW=/var/www/awesomeblog

echo "" > /home/as/awesomeblog/POST-RECEIVE_VEIKIA
git clone $GIT_REPO $TMP_GIT_CLONE

#jekyll build --source $TMP_GIT_CLONE --destination $PUBLIC_WWW
#rm -Rf $TMP_GIT_CLONE
exit
